language: python
dist: xenial
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
services:
  - redis-server
install: pip install tox-travis codecov
script: tox
after_success:
  - codecov
